"""Type definitions and shared models"""

from agentic_scraper.types.base import (
    BaseScraperConfig,
    Metadata,
)
from agentic_scraper.types.enums import (
    DataFormat,
    ScraperMethod,
    UpdateFrequency,
)
from agentic_scraper.types.errors import (
    BAAnalysisError,
    CollationError,
    GenerationError,
    OrchestrationError,
    QATestingError,
    Run1AnalysisError,
    Run2AnalysisError,
)
from agentic_scraper.types.scraper_spec import (
    APIConfig,
    EmailConfig,
    FTPConfig,
    HTTPEndpoint,
    ScraperConfig,
    ScraperSpec,
    WebsiteConfig,
    WebsiteSelector,
)

# Import BA analysis types from dedicated module
from agentic_scraper.types.ba_analysis import (
    AuthenticationMethod,
    AuthenticationSpec,
    CollationResult,
    ComplexityLevel,
    ConfidenceLevel,
    CriticalGap,
    DataSourceType,
    DocQuality,
    Endpoint,
    EndpointAnalysis,
    EndpointDetails,
    EndpointSpec,
    ExecutiveSummary,
    FilteredURLs,
    HTTPMethod,
    Parameter,
    Phase0Detection,
    Phase0IterativeAnalysis,
    Phase1Documentation,
    Phase2Tests,
    PhaseValidation,
    ResponseFormat,
    ScraperRecommendation,
    ScraperType,
    TestConclusion,
    TestResult,
    ValidatedSpec,
    ValidationOverallStatus,
    ValidationReport,
    ValidationResult,
    ValidationStatus,
    ValidationSummary,
    VisionPortalAnalysisResult,
)

__all__ = [
    # Base models
    "BaseScraperConfig",
    "Metadata",
    "ValidationResult",
    # Enums
    "AuthenticationMethod",
    "DataFormat",
    "ScraperMethod",
    "UpdateFrequency",
    # Scraper specs
    "ScraperSpec",
    "ScraperConfig",
    "APIConfig",
    "FTPConfig",
    "EmailConfig",
    "WebsiteConfig",
    "HTTPEndpoint",
    "WebsiteSelector",
    # Errors
    "OrchestrationError",
    "Run1AnalysisError",
    "Run2AnalysisError",
    "CollationError",
    "QATestingError",
    "BAAnalysisError",
    "GenerationError",
    # BA Analysis types (from types.py)
    "FilteredURLs",
    "Phase0Detection",
    "Phase0IterativeAnalysis",
    "Phase1Documentation",
    "Phase2Tests",
    "ValidatedSpec",
    "ValidationReport",
    "ValidationOverallStatus",
    "CriticalGap",
    "PhaseValidation",
    "DataSourceType",
    "EndpointSpec",
    "HTTPMethod",
    "ResponseFormat",
    "DocQuality",
    "EndpointAnalysis",
    "Endpoint",
    "EndpointDetails",
    "ExecutiveSummary",
    "ScraperRecommendation",
    "ValidationStatus",
    "ValidationSummary",
    "ConfidenceLevel",
    "ComplexityLevel",
    "ScraperType",
    "CollationResult",
    "Parameter",
    "TestResult",
    "TestConclusion",
    "AuthenticationSpec",
    # Vision analysis
    "VisionPortalAnalysisResult",
]
