# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

import baml_py

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzePhase0(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Phase0Detection:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AnalyzePhase0", llm_response=llm_response, mode="request")
        return typing.cast(types.Phase0Detection, result)

    def AnalyzePhase1(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Phase1Documentation:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AnalyzePhase1", llm_response=llm_response, mode="request")
        return typing.cast(types.Phase1Documentation, result)

    def AnalyzePhase2(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Phase2Tests:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AnalyzePhase2", llm_response=llm_response, mode="request")
        return typing.cast(types.Phase2Tests, result)

    def AnalyzePhase3(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ValidatedSpec:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AnalyzePhase3", llm_response=llm_response, mode="request")
        return typing.cast(types.ValidatedSpec, result)

    def GenerateCollectContent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.GeneratedCode:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GenerateCollectContent", llm_response=llm_response, mode="request")
        return typing.cast(types.GeneratedCode, result)

    def GenerateComplexAuth(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.GeneratedCode:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GenerateComplexAuth", llm_response=llm_response, mode="request")
        return typing.cast(types.GeneratedCode, result)

    def GenerateInitCode(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.GeneratedCode:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GenerateInitCode", llm_response=llm_response, mode="request")
        return typing.cast(types.GeneratedCode, result)

    def GenerateValidateContent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.GeneratedCode:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GenerateValidateContent", llm_response=llm_response, mode="request")
        return typing.cast(types.GeneratedCode, result)

    def MergeCompleteSpecs(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ValidatedSpec:
        result = self.__options.merge_options(baml_options).parse_response(function_name="MergeCompleteSpecs", llm_response=llm_response, mode="request")
        return typing.cast(types.ValidatedSpec, result)

    def MergePhase0(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Phase0Detection:
        result = self.__options.merge_options(baml_options).parse_response(function_name="MergePhase0", llm_response=llm_response, mode="request")
        return typing.cast(types.Phase0Detection, result)

    def ValidateCompleteSpec(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ValidationReport:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ValidateCompleteSpec", llm_response=llm_response, mode="request")
        return typing.cast(types.ValidationReport, result)

    def ValidatePhase0(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ValidationResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ValidatePhase0", llm_response=llm_response, mode="request")
        return typing.cast(types.ValidationResult, result)

    def ValidatePhase1(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ValidationResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ValidatePhase1", llm_response=llm_response, mode="request")
        return typing.cast(types.ValidationResult, result)

    def ValidatePhase2(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ValidationResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ValidatePhase2", llm_response=llm_response, mode="request")
        return typing.cast(types.ValidationResult, result)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzePhase0(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.Phase0Detection:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AnalyzePhase0", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.Phase0Detection, result)

    def AnalyzePhase1(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.Phase1Documentation:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AnalyzePhase1", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.Phase1Documentation, result)

    def AnalyzePhase2(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.Phase2Tests:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AnalyzePhase2", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.Phase2Tests, result)

    def AnalyzePhase3(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ValidatedSpec:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AnalyzePhase3", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ValidatedSpec, result)

    def GenerateCollectContent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.GeneratedCode:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GenerateCollectContent", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.GeneratedCode, result)

    def GenerateComplexAuth(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.GeneratedCode:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GenerateComplexAuth", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.GeneratedCode, result)

    def GenerateInitCode(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.GeneratedCode:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GenerateInitCode", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.GeneratedCode, result)

    def GenerateValidateContent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.GeneratedCode:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GenerateValidateContent", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.GeneratedCode, result)

    def MergeCompleteSpecs(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ValidatedSpec:
        result = self.__options.merge_options(baml_options).parse_response(function_name="MergeCompleteSpecs", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ValidatedSpec, result)

    def MergePhase0(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.Phase0Detection:
        result = self.__options.merge_options(baml_options).parse_response(function_name="MergePhase0", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.Phase0Detection, result)

    def ValidateCompleteSpec(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ValidationReport:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ValidateCompleteSpec", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ValidationReport, result)

    def ValidatePhase0(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ValidationResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ValidatePhase0", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ValidationResult, result)

    def ValidatePhase1(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ValidationResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ValidatePhase1", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ValidationResult, result)

    def ValidatePhase2(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ValidationResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ValidatePhase2", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ValidationResult, result)

    