# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (32)
# #########################################################################

class AccessRequirements(BaseModel):
    authentication: typing.Optional[str] = None
    registration: typing.Optional[typing.Dict[str, str]] = None
    terms_of_use_url: typing.Optional[str] = None
    subscription_required: typing.Optional[bool] = None
    rate_limits: typing.Optional[str] = None

class AuthClaims(BaseModel):
    auth_section_found: typing.Optional[bool] = None
    auth_section_text: typing.Optional[str] = None
    signup_links: typing.List[str]
    api_key_mentioned: typing.Optional[bool] = None
    subscription_mentioned: typing.Optional[bool] = None
    auth_header_examples: typing.List[str]
    conclusion: typing.Optional[str] = None

class AuthenticationFindings(BaseModel):
    auth_required: typing.Optional[bool] = None
    evidence: typing.Optional[str] = None
    cookie_required: typing.Optional[bool] = None
    redirect_to_login: typing.Optional[bool] = None
    auth_headers_found: typing.List[str]

class AuthenticationSpec(BaseModel):
    required: typing.Optional[bool] = None
    method: typing.Optional[types.AuthenticationMethod] = None
    header_name: typing.Optional[str] = None
    evidence: typing.Optional[str] = None
    registration_url: typing.Optional[str] = None
    notes: typing.Optional[str] = None
    authentication_consistency: typing.Optional[bool] = None
    authentication_notes: typing.Optional[str] = None
    authentication_details: typing.Optional[str] = None

class CollationAnalysis(BaseModel):
    run_comparison: typing.Dict[str, str]
    improvements_from_run2: typing.List[str]
    discrepancies_resolved: typing.List[typing.Dict[str, str]]
    consistency_checks: typing.Dict[str, str]

class CollationMetadata(BaseModel):
    collation_timestamp: typing.Optional[str] = None
    run1_timestamp: typing.Optional[str] = None
    run2_timestamp: typing.Optional[str] = None
    validation_report: typing.Optional[str] = None
    runs_compared: typing.Optional[int] = None
    collation_agent: typing.Optional[str] = None

class CollationResult(BaseModel):
    collation_complete: typing.Optional[bool] = None
    final_spec_path: typing.Optional[str] = None
    final_confidence_score: typing.Optional[float] = None
    total_endpoints: typing.Optional[int] = None
    endpoints_run1: typing.Optional[int] = None
    endpoints_run2: typing.Optional[int] = None
    improvements_count: typing.Optional[int] = None
    discrepancies_resolved: typing.Optional[int] = None
    consistency_rate: typing.Optional[str] = None
    ready_for_scraper_generation: typing.Optional[bool] = None

class CriticalGap(BaseModel):
    gap_type: typing.Optional[str] = None
    description: typing.Optional[str] = None
    action_required: typing.Optional[str] = None
    discovered: typing.Optional[int] = None
    documented: typing.Optional[int] = None
    missing: typing.Optional[int] = None

class DataCatalog(BaseModel):
    total_files_discovered: typing.Optional[int] = None
    total_endpoints: typing.Optional[int] = None
    file_formats: typing.Dict[str, int]
    data_categories: typing.List[str]
    downloadable_files: typing.List[typing.Dict[str, str]]

class DataInventory(BaseModel):
    total_files: typing.Optional[int] = None
    file_formats: typing.List[str]
    categories: typing.List[str]
    download_links: typing.List[typing.Dict[str, str]]

class Discrepancy(BaseModel):
    type: typing.Optional[str] = None
    documentation_said: typing.Optional[str] = None
    api_testing_showed: typing.Optional[str] = None
    severity: typing.Optional[str] = None
    resolution: typing.Optional[str] = None
    area: typing.Optional[str] = None
    phase1_claim: typing.Optional[str] = None
    phase2_finding: typing.Optional[str] = None

class DownloadTest(BaseModel):
    url: typing.Optional[str] = None
    http_status: typing.Optional[int] = None
    content_type: typing.Optional[str] = None
    content_length: typing.Optional[str] = None
    last_modified: typing.Optional[str] = None
    accessible: typing.Optional[bool] = None
    requires_auth: typing.Optional[bool] = None
    redirect_to_login: typing.Optional[bool] = None

class Endpoint(BaseModel):
    path: typing.Optional[str] = None
    method: typing.Optional[types.HTTPMethod] = None
    parameters: typing.List["Parameter"]
    auth_required: typing.Optional[bool] = None
    response_format: typing.Optional[types.ResponseFormat] = None

class EndpointDetails(BaseModel):
    endpoint_id: typing.Optional[str] = None
    name: typing.Optional[str] = None
    type: typing.Optional[str] = None
    base_url: typing.Optional[str] = None
    path: typing.Optional[str] = None
    method: typing.Optional[types.HTTPMethod] = None
    parameters: typing.Dict[str, "Parameter"]
    authentication: typing.Dict[str, str]
    response_format: typing.Optional[types.ResponseFormat] = None
    data_structure: typing.Optional[typing.Dict[str, str]] = None
    sample_files: typing.Optional[typing.List[typing.Dict[str, str]]] = None
    validation_status: typing.Optional[types.ValidationStatus] = None
    accessible: typing.Optional[bool] = None
    last_tested: typing.Optional[str] = None
    file_count: typing.Optional[int] = None
    update_frequency: typing.Optional[str] = None
    notes: typing.Optional[str] = None
    validation_consistency: typing.Optional[str] = None
    tested_in_run1: typing.Optional[bool] = None
    tested_in_run2: typing.Optional[bool] = None

class EndpointDiscovery(BaseModel):
    total_endpoints_found: typing.Optional[int] = None
    collapsible_sections_expanded: typing.Optional[int] = None
    extraction_method: typing.Optional[str] = None
    screenshot_taken: typing.Optional[bool] = None
    systematic_enumeration_completed: typing.Optional[bool] = None

class EndpointSpec(BaseModel):
    endpoint_id: typing.Optional[str] = None
    path: typing.Optional[str] = None
    method: typing.Optional[types.HTTPMethod] = None
    description: typing.Optional[str] = None
    parameters: typing.List["Parameter"]
    response_format: typing.Optional[types.ResponseFormat] = None
    authentication_mentioned: typing.Optional[bool] = None

class ExecutiveSummary(BaseModel):
    total_endpoints_discovered: typing.Optional[int] = None
    total_datasets: typing.Optional[int] = None
    total_files: typing.Optional[int] = None
    accessible_endpoints: typing.Optional[int] = None
    protected_endpoints: typing.Optional[int] = None
    broken_endpoints: typing.Optional[int] = None
    success_rate: typing.Optional[str] = None
    primary_formats: typing.List[str]
    authentication_required: typing.Optional[bool] = None
    estimated_scraper_complexity: typing.Optional[types.ComplexityLevel] = None
    improvements_from_run1: typing.Optional[typing.Dict[str, str]] = None

class FileMetadataVerification(BaseModel):
    file_sizes_match_claims: typing.Optional[str] = None
    content_types_match: typing.Optional[bool] = None
    last_modified_dates_available: typing.Optional[bool] = None

class GeneratedCode(BaseModel):
    code: typing.Optional[str] = None
    imports: typing.List[str]
    notes: typing.Optional[str] = None

class Parameter(BaseModel):
    name: typing.Optional[str] = None
    type: typing.Optional[str] = None
    required: typing.Optional[bool] = None
    description: typing.Optional[str] = None
    example: typing.Optional[str] = None

class Phase0Detection(BaseModel):
    detected_type: typing.Optional[types.DataSourceType] = None
    confidence: typing.Optional[float] = None
    indicators: typing.List[str]
    discovered_api_calls: typing.List[str]
    endpoints: typing.List["Endpoint"]
    url: typing.Optional[str] = None
    fallback_strategy: typing.Optional[str] = None

class Phase1Documentation(BaseModel):
    source: typing.Optional[str] = None
    timestamp: typing.Optional[str] = None
    url: typing.Optional[str] = None
    endpoint_discovery: typing.Optional["EndpointDiscovery"] = None
    auth_claims: typing.Optional["AuthClaims"] = None
    endpoints: typing.List["EndpointSpec"]
    doc_quality: typing.Optional[types.DocQuality] = None
    notes: typing.Optional[str] = None
    source_type: typing.Optional[str] = None
    data_inventory: typing.Optional["DataInventory"] = None
    access_requirements: typing.Optional["AccessRequirements"] = None
    update_frequency: typing.Optional[str] = None
    portal_type: typing.Optional[types.PortalType] = None
    extraction_quality: typing.Optional[types.ExtractionQuality] = None

class Phase2Tests(BaseModel):
    source: typing.Optional[str] = None
    timestamp: typing.Optional[str] = None
    endpoint_tested: typing.Optional[str] = None
    test_results: typing.Optional[typing.Dict[str, "TestResult"]] = None
    conclusion: typing.Optional["TestConclusion"] = None
    files_saved: typing.List[str]
    source_type: typing.Optional[str] = None
    download_tests: typing.Optional[typing.Dict[str, typing.List["DownloadTest"]]] = None
    authentication_findings: typing.Optional["AuthenticationFindings"] = None
    file_metadata_verification: typing.Optional["FileMetadataVerification"] = None
    portal_type: typing.Optional[types.PortalType] = None
    portal_conclusion: typing.Optional[str] = None

class PhaseValidation(BaseModel):
    status: typing.Optional[types.ValidationOverallStatus] = None
    issues: typing.List[typing.Dict[str, str]]
    notes: typing.Optional[str] = None

class ScraperRecommendation(BaseModel):
    type: typing.Optional[types.ScraperType] = None
    confidence: typing.Optional[types.ConfidenceLevel] = None
    rationale: typing.List[str]
    complexity: typing.Optional[types.ComplexityLevel] = None
    estimated_effort: typing.Optional[str] = None
    key_challenges: typing.List[str]

class TestConclusion(BaseModel):
    auth_required: typing.Optional[bool] = None
    evidence: typing.Optional[str] = None
    likely_auth_method: typing.Optional[types.AuthenticationMethod] = None
    likely_header_name: typing.Optional[str] = None
    confidence: typing.Optional[types.ConfidenceLevel] = None

class TestResult(BaseModel):
    http_status: typing.Optional[int] = None
    response_snippet: typing.Optional[str] = None
    auth_keywords_found: typing.List[str]
    full_output_file: typing.Optional[str] = None

class ValidatedSpec(BaseModel):
    source: typing.Optional[str] = None
    source_type: typing.Optional[str] = None
    timestamp: typing.Optional[str] = None
    url: typing.Optional[str] = None
    executive_summary: typing.Optional["ExecutiveSummary"] = None
    validation_summary: typing.Optional["ValidationSummary"] = None
    authentication: typing.Optional["AuthenticationSpec"] = None
    access_requirements: typing.Optional["AccessRequirements"] = None
    endpoints: typing.List["EndpointDetails"]
    data_catalog: typing.Optional["DataCatalog"] = None
    scraper_recommendation: typing.Optional["ScraperRecommendation"] = None
    discrepancies: typing.List["Discrepancy"]
    artifacts_generated: typing.List[str]
    next_steps: typing.List[str]
    collation_metadata: typing.Optional["CollationMetadata"] = None
    collation_analysis: typing.Optional["CollationAnalysis"] = None

class ValidationReport(BaseModel):
    validation_timestamp: typing.Optional[str] = None
    input_file: typing.Optional[str] = None
    overall_status: typing.Optional[types.ValidationOverallStatus] = None
    overall_confidence: typing.Optional[float] = None
    phase_validations: typing.Dict[str, "PhaseValidation"]
    critical_gaps: typing.List["CriticalGap"]
    recommendations_for_second_pass: typing.List[str]
    validation_summary: typing.Optional[str] = None

class ValidationResult(BaseModel):
    confidence: typing.Optional[float] = None
    identified_gaps: typing.List[str]
    recommendations: typing.List[str]
    validation_notes: typing.Optional[str] = None

class ValidationRules(BaseModel):
    required_fields: typing.List[str]
    format_checks: typing.List[str]
    range_checks: typing.List[str]
    custom_logic: typing.Optional[str] = None

class ValidationSummary(BaseModel):
    phases_completed: typing.List[str]
    documentation_review: typing.Optional[str] = None
    live_api_testing: typing.Optional[str] = None
    discrepancies_found: typing.Optional[int] = None
    confidence_score: typing.Optional[float] = None
    confidence_level: typing.Optional[types.ConfidenceLevel] = None
    recommendation: typing.Optional[str] = None
    collation_complete: typing.Optional[bool] = None
    runs_analyzed: typing.Optional[int] = None
    final_confidence_score: typing.Optional[float] = None
    run1_confidence: typing.Optional[float] = None
    run2_confidence: typing.Optional[float] = None
    confidence_consistency: typing.Optional[str] = None
    validator_status: typing.Optional[str] = None
    discrepancies_resolved: typing.Optional[int] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
