# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__

class BamlSyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def __getstate__(self):
        # Return state needed for pickling
        return {"options": self.__options}

    def __setstate__(self, state):
        # Restore state from pickling
        self.__options = state["options"]
        self.__stream_client = BamlStreamClient(self.__options)
        self.__http_request = BamlHttpRequestClient(self.__options)
        self.__http_stream_request = BamlHttpStreamRequestClient(self.__options)
        self.__llm_response_parser = LlmResponseParser(self.__options)
        self.__llm_stream_parser = LlmStreamParser(self.__options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlSyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlSyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser
    
    def AnalyzePhase0(self, url: str,html_content: str,network_calls: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> types.Phase0Detection:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.AnalyzePhase0(url=url,html_content=html_content,network_calls=network_calls,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="AnalyzePhase0", args={
                "url": url,"html_content": html_content,"network_calls": network_calls,
            })
            return typing.cast(types.Phase0Detection, result.cast_to(types, types, stream_types, False, __runtime__))
    def AnalyzePhase1(self, url: str,documentation_content: str,phase0_result: types.Phase0Detection,
        baml_options: BamlCallOptions = {},
    ) -> types.Phase1Documentation:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.AnalyzePhase1(url=url,documentation_content=documentation_content,phase0_result=phase0_result,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="AnalyzePhase1", args={
                "url": url,"documentation_content": documentation_content,"phase0_result": phase0_result,
            })
            return typing.cast(types.Phase1Documentation, result.cast_to(types, types, stream_types, False, __runtime__))
    def AnalyzePhase2(self, url: str,test_results_content: str,phase0_result: types.Phase0Detection,phase1_result: types.Phase1Documentation,
        baml_options: BamlCallOptions = {},
    ) -> types.Phase2Tests:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.AnalyzePhase2(url=url,test_results_content=test_results_content,phase0_result=phase0_result,phase1_result=phase1_result,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="AnalyzePhase2", args={
                "url": url,"test_results_content": test_results_content,"phase0_result": phase0_result,"phase1_result": phase1_result,
            })
            return typing.cast(types.Phase2Tests, result.cast_to(types, types, stream_types, False, __runtime__))
    def AnalyzePhase3(self, url: str,phase0: types.Phase0Detection,phase1: types.Phase1Documentation,phase2: types.Phase2Tests,
        baml_options: BamlCallOptions = {},
    ) -> types.ValidatedSpec:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.AnalyzePhase3(url=url,phase0=phase0,phase1=phase1,phase2=phase2,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="AnalyzePhase3", args={
                "url": url,"phase0": phase0,"phase1": phase1,"phase2": phase2,
            })
            return typing.cast(types.ValidatedSpec, result.cast_to(types, types, stream_types, False, __runtime__))
    def MergeCompleteSpecs(self, run1: types.ValidatedSpec,run2: types.ValidatedSpec,
        baml_options: BamlCallOptions = {},
    ) -> types.ValidatedSpec:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.MergeCompleteSpecs(run1=run1,run2=run2,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="MergeCompleteSpecs", args={
                "run1": run1,"run2": run2,
            })
            return typing.cast(types.ValidatedSpec, result.cast_to(types, types, stream_types, False, __runtime__))
    def MergePhase0(self, run1: types.Phase0Detection,run2: types.Phase0Detection,run2_focus_areas: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> types.Phase0Detection:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.MergePhase0(run1=run1,run2=run2,run2_focus_areas=run2_focus_areas,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="MergePhase0", args={
                "run1": run1,"run2": run2,"run2_focus_areas": run2_focus_areas,
            })
            return typing.cast(types.Phase0Detection, result.cast_to(types, types, stream_types, False, __runtime__))
    def ValidateCompleteSpec(self, spec: types.ValidatedSpec,
        baml_options: BamlCallOptions = {},
    ) -> types.ValidationReport:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ValidateCompleteSpec(spec=spec,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ValidateCompleteSpec", args={
                "spec": spec,
            })
            return typing.cast(types.ValidationReport, result.cast_to(types, types, stream_types, False, __runtime__))
    def ValidatePhase0(self, phase0_result: types.Phase0Detection,original_url: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ValidationResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ValidatePhase0(phase0_result=phase0_result,original_url=original_url,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ValidatePhase0", args={
                "phase0_result": phase0_result,"original_url": original_url,
            })
            return typing.cast(types.ValidationResult, result.cast_to(types, types, stream_types, False, __runtime__))
    def ValidatePhase1(self, phase1_result: types.Phase1Documentation,phase0_result: types.Phase0Detection,
        baml_options: BamlCallOptions = {},
    ) -> types.ValidationResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ValidatePhase1(phase1_result=phase1_result,phase0_result=phase0_result,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ValidatePhase1", args={
                "phase1_result": phase1_result,"phase0_result": phase0_result,
            })
            return typing.cast(types.ValidationResult, result.cast_to(types, types, stream_types, False, __runtime__))
    def ValidatePhase2(self, phase2_result: types.Phase2Tests,phase1_result: types.Phase1Documentation,
        baml_options: BamlCallOptions = {},
    ) -> types.ValidationResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ValidatePhase2(phase2_result=phase2_result,phase1_result=phase1_result,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ValidatePhase2", args={
                "phase2_result": phase2_result,"phase1_result": phase1_result,
            })
            return typing.cast(types.ValidationResult, result.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzePhase0(self, url: str,html_content: str,network_calls: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.Phase0Detection, types.Phase0Detection]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="AnalyzePhase0", args={
            "url": url,"html_content": html_content,"network_calls": network_calls,
        })
        return baml_py.BamlSyncStream[stream_types.Phase0Detection, types.Phase0Detection](
          result,
          lambda x: typing.cast(stream_types.Phase0Detection, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.Phase0Detection, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def AnalyzePhase1(self, url: str,documentation_content: str,phase0_result: types.Phase0Detection,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.Phase1Documentation, types.Phase1Documentation]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="AnalyzePhase1", args={
            "url": url,"documentation_content": documentation_content,"phase0_result": phase0_result,
        })
        return baml_py.BamlSyncStream[stream_types.Phase1Documentation, types.Phase1Documentation](
          result,
          lambda x: typing.cast(stream_types.Phase1Documentation, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.Phase1Documentation, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def AnalyzePhase2(self, url: str,test_results_content: str,phase0_result: types.Phase0Detection,phase1_result: types.Phase1Documentation,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.Phase2Tests, types.Phase2Tests]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="AnalyzePhase2", args={
            "url": url,"test_results_content": test_results_content,"phase0_result": phase0_result,"phase1_result": phase1_result,
        })
        return baml_py.BamlSyncStream[stream_types.Phase2Tests, types.Phase2Tests](
          result,
          lambda x: typing.cast(stream_types.Phase2Tests, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.Phase2Tests, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def AnalyzePhase3(self, url: str,phase0: types.Phase0Detection,phase1: types.Phase1Documentation,phase2: types.Phase2Tests,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.ValidatedSpec, types.ValidatedSpec]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="AnalyzePhase3", args={
            "url": url,"phase0": phase0,"phase1": phase1,"phase2": phase2,
        })
        return baml_py.BamlSyncStream[stream_types.ValidatedSpec, types.ValidatedSpec](
          result,
          lambda x: typing.cast(stream_types.ValidatedSpec, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ValidatedSpec, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def MergeCompleteSpecs(self, run1: types.ValidatedSpec,run2: types.ValidatedSpec,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.ValidatedSpec, types.ValidatedSpec]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="MergeCompleteSpecs", args={
            "run1": run1,"run2": run2,
        })
        return baml_py.BamlSyncStream[stream_types.ValidatedSpec, types.ValidatedSpec](
          result,
          lambda x: typing.cast(stream_types.ValidatedSpec, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ValidatedSpec, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def MergePhase0(self, run1: types.Phase0Detection,run2: types.Phase0Detection,run2_focus_areas: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.Phase0Detection, types.Phase0Detection]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="MergePhase0", args={
            "run1": run1,"run2": run2,"run2_focus_areas": run2_focus_areas,
        })
        return baml_py.BamlSyncStream[stream_types.Phase0Detection, types.Phase0Detection](
          result,
          lambda x: typing.cast(stream_types.Phase0Detection, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.Phase0Detection, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ValidateCompleteSpec(self, spec: types.ValidatedSpec,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.ValidationReport, types.ValidationReport]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ValidateCompleteSpec", args={
            "spec": spec,
        })
        return baml_py.BamlSyncStream[stream_types.ValidationReport, types.ValidationReport](
          result,
          lambda x: typing.cast(stream_types.ValidationReport, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ValidationReport, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ValidatePhase0(self, phase0_result: types.Phase0Detection,original_url: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.ValidationResult, types.ValidationResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ValidatePhase0", args={
            "phase0_result": phase0_result,"original_url": original_url,
        })
        return baml_py.BamlSyncStream[stream_types.ValidationResult, types.ValidationResult](
          result,
          lambda x: typing.cast(stream_types.ValidationResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ValidationResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ValidatePhase1(self, phase1_result: types.Phase1Documentation,phase0_result: types.Phase0Detection,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.ValidationResult, types.ValidationResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ValidatePhase1", args={
            "phase1_result": phase1_result,"phase0_result": phase0_result,
        })
        return baml_py.BamlSyncStream[stream_types.ValidationResult, types.ValidationResult](
          result,
          lambda x: typing.cast(stream_types.ValidationResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ValidationResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ValidatePhase2(self, phase2_result: types.Phase2Tests,phase1_result: types.Phase1Documentation,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.ValidationResult, types.ValidationResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ValidatePhase2", args={
            "phase2_result": phase2_result,"phase1_result": phase1_result,
        })
        return baml_py.BamlSyncStream[stream_types.ValidationResult, types.ValidationResult](
          result,
          lambda x: typing.cast(stream_types.ValidationResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ValidationResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzePhase0(self, url: str,html_content: str,network_calls: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="AnalyzePhase0", args={
            "url": url,"html_content": html_content,"network_calls": network_calls,
        }, mode="request")
        return result
    def AnalyzePhase1(self, url: str,documentation_content: str,phase0_result: types.Phase0Detection,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="AnalyzePhase1", args={
            "url": url,"documentation_content": documentation_content,"phase0_result": phase0_result,
        }, mode="request")
        return result
    def AnalyzePhase2(self, url: str,test_results_content: str,phase0_result: types.Phase0Detection,phase1_result: types.Phase1Documentation,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="AnalyzePhase2", args={
            "url": url,"test_results_content": test_results_content,"phase0_result": phase0_result,"phase1_result": phase1_result,
        }, mode="request")
        return result
    def AnalyzePhase3(self, url: str,phase0: types.Phase0Detection,phase1: types.Phase1Documentation,phase2: types.Phase2Tests,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="AnalyzePhase3", args={
            "url": url,"phase0": phase0,"phase1": phase1,"phase2": phase2,
        }, mode="request")
        return result
    def MergeCompleteSpecs(self, run1: types.ValidatedSpec,run2: types.ValidatedSpec,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="MergeCompleteSpecs", args={
            "run1": run1,"run2": run2,
        }, mode="request")
        return result
    def MergePhase0(self, run1: types.Phase0Detection,run2: types.Phase0Detection,run2_focus_areas: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="MergePhase0", args={
            "run1": run1,"run2": run2,"run2_focus_areas": run2_focus_areas,
        }, mode="request")
        return result
    def ValidateCompleteSpec(self, spec: types.ValidatedSpec,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ValidateCompleteSpec", args={
            "spec": spec,
        }, mode="request")
        return result
    def ValidatePhase0(self, phase0_result: types.Phase0Detection,original_url: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ValidatePhase0", args={
            "phase0_result": phase0_result,"original_url": original_url,
        }, mode="request")
        return result
    def ValidatePhase1(self, phase1_result: types.Phase1Documentation,phase0_result: types.Phase0Detection,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ValidatePhase1", args={
            "phase1_result": phase1_result,"phase0_result": phase0_result,
        }, mode="request")
        return result
    def ValidatePhase2(self, phase2_result: types.Phase2Tests,phase1_result: types.Phase1Documentation,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ValidatePhase2", args={
            "phase2_result": phase2_result,"phase1_result": phase1_result,
        }, mode="request")
        return result
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzePhase0(self, url: str,html_content: str,network_calls: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="AnalyzePhase0", args={
            "url": url,"html_content": html_content,"network_calls": network_calls,
        }, mode="stream")
        return result
    def AnalyzePhase1(self, url: str,documentation_content: str,phase0_result: types.Phase0Detection,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="AnalyzePhase1", args={
            "url": url,"documentation_content": documentation_content,"phase0_result": phase0_result,
        }, mode="stream")
        return result
    def AnalyzePhase2(self, url: str,test_results_content: str,phase0_result: types.Phase0Detection,phase1_result: types.Phase1Documentation,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="AnalyzePhase2", args={
            "url": url,"test_results_content": test_results_content,"phase0_result": phase0_result,"phase1_result": phase1_result,
        }, mode="stream")
        return result
    def AnalyzePhase3(self, url: str,phase0: types.Phase0Detection,phase1: types.Phase1Documentation,phase2: types.Phase2Tests,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="AnalyzePhase3", args={
            "url": url,"phase0": phase0,"phase1": phase1,"phase2": phase2,
        }, mode="stream")
        return result
    def MergeCompleteSpecs(self, run1: types.ValidatedSpec,run2: types.ValidatedSpec,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="MergeCompleteSpecs", args={
            "run1": run1,"run2": run2,
        }, mode="stream")
        return result
    def MergePhase0(self, run1: types.Phase0Detection,run2: types.Phase0Detection,run2_focus_areas: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="MergePhase0", args={
            "run1": run1,"run2": run2,"run2_focus_areas": run2_focus_areas,
        }, mode="stream")
        return result
    def ValidateCompleteSpec(self, spec: types.ValidatedSpec,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ValidateCompleteSpec", args={
            "spec": spec,
        }, mode="stream")
        return result
    def ValidatePhase0(self, phase0_result: types.Phase0Detection,original_url: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ValidatePhase0", args={
            "phase0_result": phase0_result,"original_url": original_url,
        }, mode="stream")
        return result
    def ValidatePhase1(self, phase1_result: types.Phase1Documentation,phase0_result: types.Phase0Detection,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ValidatePhase1", args={
            "phase1_result": phase1_result,"phase0_result": phase0_result,
        }, mode="stream")
        return result
    def ValidatePhase2(self, phase2_result: types.Phase2Tests,phase1_result: types.Phase1Documentation,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ValidatePhase2", args={
            "phase2_result": phase2_result,"phase1_result": phase1_result,
        }, mode="stream")
        return result
    

b = BamlSyncClient(DoNotUseDirectlyCallManager({}))