# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.AccessRequirements": types.AccessRequirements,
    "stream_types.AccessRequirements": stream_types.AccessRequirements,

    "types.AuthClaims": types.AuthClaims,
    "stream_types.AuthClaims": stream_types.AuthClaims,

    "types.AuthenticationFindings": types.AuthenticationFindings,
    "stream_types.AuthenticationFindings": stream_types.AuthenticationFindings,

    "types.AuthenticationSpec": types.AuthenticationSpec,
    "stream_types.AuthenticationSpec": stream_types.AuthenticationSpec,

    "types.CollationAnalysis": types.CollationAnalysis,
    "stream_types.CollationAnalysis": stream_types.CollationAnalysis,

    "types.CollationMetadata": types.CollationMetadata,
    "stream_types.CollationMetadata": stream_types.CollationMetadata,

    "types.CollationResult": types.CollationResult,
    "stream_types.CollationResult": stream_types.CollationResult,

    "types.CriticalGap": types.CriticalGap,
    "stream_types.CriticalGap": stream_types.CriticalGap,

    "types.DataCatalog": types.DataCatalog,
    "stream_types.DataCatalog": stream_types.DataCatalog,

    "types.DataInventory": types.DataInventory,
    "stream_types.DataInventory": stream_types.DataInventory,

    "types.Discrepancy": types.Discrepancy,
    "stream_types.Discrepancy": stream_types.Discrepancy,

    "types.DownloadTest": types.DownloadTest,
    "stream_types.DownloadTest": stream_types.DownloadTest,

    "types.Endpoint": types.Endpoint,
    "stream_types.Endpoint": stream_types.Endpoint,

    "types.EndpointDetails": types.EndpointDetails,
    "stream_types.EndpointDetails": stream_types.EndpointDetails,

    "types.EndpointDiscovery": types.EndpointDiscovery,
    "stream_types.EndpointDiscovery": stream_types.EndpointDiscovery,

    "types.EndpointSpec": types.EndpointSpec,
    "stream_types.EndpointSpec": stream_types.EndpointSpec,

    "types.ExecutiveSummary": types.ExecutiveSummary,
    "stream_types.ExecutiveSummary": stream_types.ExecutiveSummary,

    "types.FileMetadataVerification": types.FileMetadataVerification,
    "stream_types.FileMetadataVerification": stream_types.FileMetadataVerification,

    "types.Parameter": types.Parameter,
    "stream_types.Parameter": stream_types.Parameter,

    "types.Phase0Detection": types.Phase0Detection,
    "stream_types.Phase0Detection": stream_types.Phase0Detection,

    "types.Phase1Documentation": types.Phase1Documentation,
    "stream_types.Phase1Documentation": stream_types.Phase1Documentation,

    "types.Phase2Tests": types.Phase2Tests,
    "stream_types.Phase2Tests": stream_types.Phase2Tests,

    "types.PhaseValidation": types.PhaseValidation,
    "stream_types.PhaseValidation": stream_types.PhaseValidation,

    "types.ScraperRecommendation": types.ScraperRecommendation,
    "stream_types.ScraperRecommendation": stream_types.ScraperRecommendation,

    "types.TestConclusion": types.TestConclusion,
    "stream_types.TestConclusion": stream_types.TestConclusion,

    "types.TestResult": types.TestResult,
    "stream_types.TestResult": stream_types.TestResult,

    "types.ValidatedSpec": types.ValidatedSpec,
    "stream_types.ValidatedSpec": stream_types.ValidatedSpec,

    "types.ValidationReport": types.ValidationReport,
    "stream_types.ValidationReport": stream_types.ValidationReport,

    "types.ValidationResult": types.ValidationResult,
    "stream_types.ValidationResult": stream_types.ValidationResult,

    "types.ValidationSummary": types.ValidationSummary,
    "stream_types.ValidationSummary": stream_types.ValidationSummary,


    "types.AuthenticationMethod": types.AuthenticationMethod,

    "types.ComplexityLevel": types.ComplexityLevel,

    "types.ConfidenceLevel": types.ConfidenceLevel,

    "types.DataSourceType": types.DataSourceType,

    "types.DocQuality": types.DocQuality,

    "types.ExtractionQuality": types.ExtractionQuality,

    "types.HTTPMethod": types.HTTPMethod,

    "types.ParameterLocation": types.ParameterLocation,

    "types.PortalType": types.PortalType,

    "types.ResponseFormat": types.ResponseFormat,

    "types.ScraperType": types.ScraperType,

    "types.ValidationOverallStatus": types.ValidationOverallStatus,

    "types.ValidationStatus": types.ValidationStatus,

}