/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  AccessRequirements,  AuthClaims,  AuthenticationFindings,  AuthenticationMethod,  AuthenticationSpec,  CollationAnalysis,  CollationMetadata,  CollationResult,  ComplexityLevel,  ConfidenceLevel,  CriticalGap,  DataCatalog,  DataInventory,  DataSourceType,  Discrepancy,  DownloadTest,  Endpoint,  EndpointDetails,  EndpointDiscovery,  EndpointSpec,  ExecutiveSummary,  ExtractionQuality,  FileMetadataVerification,  HTTPMethod,  Parameter,  Phase0Detection,  Phase1Documentation,  Phase2Tests,  PhaseValidation,  ScraperRecommendation,  ScraperType,  TestConclusion,  TestResult,  ValidatedSpec,  ValidationOverallStatus,  ValidationReport,  ValidationStatus,  ValidationSummary } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface AccessRequirements {
      authentication?: string | null
      registration?: Record<string, string> | null
      terms_of_use_url?: string | null
      subscription_required?: boolean | null
      rate_limits?: string | null
    }
    export interface AuthClaims {
      auth_section_found?: boolean | null
      auth_section_text?: string | null
      signup_links: string[]
      api_key_mentioned?: boolean | null
      subscription_mentioned?: boolean | null
      auth_header_examples: string[]
      conclusion?: string | null
    }
    export interface AuthenticationFindings {
      auth_required?: boolean | null
      evidence?: string | null
      cookie_required?: boolean | null
      redirect_to_login?: boolean | null
      auth_headers_found: string[]
    }
    export interface AuthenticationSpec {
      required?: boolean | null
      method?: types.AuthenticationMethod | null
      header_name?: string | null
      evidence?: string | null
      registration_url?: string | null
      notes?: string | null
      authentication_consistency?: boolean | null
      authentication_notes?: string | null
      authentication_details?: string | null
    }
    export interface CollationAnalysis {
      run_comparison: Record<string, string>
      improvements_from_run2: string[]
      discrepancies_resolved: Record<string, string>[]
      consistency_checks: Record<string, string>
    }
    export interface CollationMetadata {
      collation_timestamp?: string | null
      run1_timestamp?: string | null
      run2_timestamp?: string | null
      validation_report?: string | null
      runs_compared?: number | null
      collation_agent?: string | null
    }
    export interface CollationResult {
      collation_complete?: boolean | null
      final_spec_path?: string | null
      final_confidence_score?: number | null
      total_endpoints?: number | null
      endpoints_run1?: number | null
      endpoints_run2?: number | null
      improvements_count?: number | null
      discrepancies_resolved?: number | null
      consistency_rate?: string | null
      ready_for_scraper_generation?: boolean | null
    }
    export interface CriticalGap {
      gap_type?: string | null
      description?: string | null
      action_required?: string | null
      discovered?: number | null
      documented?: number | null
      missing?: number | null
    }
    export interface DataCatalog {
      total_files_discovered?: number | null
      total_endpoints?: number | null
      file_formats: Record<string, number>
      data_categories: string[]
      downloadable_files: Record<string, string>[]
    }
    export interface DataInventory {
      total_files?: number | null
      file_formats: string[]
      categories: string[]
      download_links: Record<string, string>[]
    }
    export interface Discrepancy {
      type?: string | null
      documentation_said?: string | null
      api_testing_showed?: string | null
      severity?: string | null
      resolution?: string | null
      area?: string | null
      phase1_claim?: string | null
      phase2_finding?: string | null
    }
    export interface DownloadTest {
      url?: string | null
      http_status?: number | null
      content_type?: string | null
      content_length?: string | null
      last_modified?: string | null
      accessible?: boolean | null
      requires_auth?: boolean | null
      redirect_to_login?: boolean | null
    }
    export interface Endpoint {
      path?: string | null
      method?: types.HTTPMethod | null
      parameters: Parameter[]
      auth_required?: boolean | null
      response_format?: string | null
    }
    export interface EndpointDetails {
      endpoint_id?: string | null
      name?: string | null
      type?: string | null
      base_url?: string | null
      path?: string | null
      method?: types.HTTPMethod | null
      parameters: Record<string, Parameter>
      authentication: Record<string, string>
      response_format?: string | null
      data_structure?: Record<string, string> | null
      sample_files?: Record<string, string>[] | null
      validation_status?: types.ValidationStatus | null
      accessible?: boolean | null
      last_tested?: string | null
      file_count?: number | null
      update_frequency?: string | null
      notes?: string | null
      validation_consistency?: string | null
      tested_in_run1?: boolean | null
      tested_in_run2?: boolean | null
    }
    export interface EndpointDiscovery {
      total_endpoints_found?: number | null
      collapsible_sections_expanded?: number | null
      extraction_method?: string | null
      screenshot_taken?: boolean | null
      systematic_enumeration_completed?: boolean | null
    }
    export interface EndpointSpec {
      endpoint_id?: string | null
      path?: string | null
      method?: types.HTTPMethod | null
      description?: string | null
      parameters: Parameter[]
      response_format?: string | null
      authentication_mentioned?: boolean | null
    }
    export interface ExecutiveSummary {
      total_endpoints_discovered?: number | null
      total_datasets?: number | null
      total_files?: number | null
      accessible_endpoints?: number | null
      protected_endpoints?: number | null
      broken_endpoints?: number | null
      success_rate?: string | null
      primary_formats: string[]
      authentication_required?: boolean | null
      estimated_scraper_complexity?: types.ComplexityLevel | null
      improvements_from_run1?: Record<string, string> | null
    }
    export interface FileMetadataVerification {
      file_sizes_match_claims?: string | null
      content_types_match?: boolean | null
      last_modified_dates_available?: boolean | null
    }
    export interface Parameter {
      name?: string | null
      type?: string | null
      required?: boolean | null
      description?: string | null
      example?: string | null
    }
    export interface Phase0Detection {
      detected_type?: types.DataSourceType | null
      confidence?: number | null
      indicators: string[]
      discovered_api_calls: string[]
      endpoints: Endpoint[]
      url?: string | null
      fallback_strategy?: string | null
    }
    export interface Phase1Documentation {
      source?: string | null
      timestamp?: string | null
      url?: string | null
      endpoint_discovery?: EndpointDiscovery | null
      auth_claims?: AuthClaims | null
      endpoints: EndpointSpec[]
      doc_quality?: string | null
      notes?: string | null
      source_type?: string | null
      data_inventory?: DataInventory | null
      access_requirements?: AccessRequirements | null
      update_frequency?: string | null
      portal_type?: string | null
      extraction_quality?: types.ExtractionQuality | null
    }
    export interface Phase2Tests {
      source?: string | null
      timestamp?: string | null
      endpoint_tested?: string | null
      test_results?: Record<string, TestResult> | null
      conclusion?: TestConclusion | null
      files_saved: string[]
      source_type?: string | null
      download_tests?: Record<string, DownloadTest[]> | null
      authentication_findings?: AuthenticationFindings | null
      file_metadata_verification?: FileMetadataVerification | null
    }
    export interface PhaseValidation {
      status?: types.ValidationOverallStatus | null
      issues: Record<string, string>[]
      notes?: string | null
    }
    export interface ScraperRecommendation {
      type?: types.ScraperType | null
      confidence?: types.ConfidenceLevel | null
      rationale: string[]
      complexity?: types.ComplexityLevel | null
      estimated_effort?: string | null
      key_challenges: string[]
    }
    export interface TestConclusion {
      auth_required?: boolean | null
      evidence?: string | null
      likely_auth_method?: types.AuthenticationMethod | null
      likely_header_name?: string | null
      confidence?: types.ConfidenceLevel | null
    }
    export interface TestResult {
      http_status?: number | null
      response_snippet?: string | null
      auth_keywords_found: string[]
      full_output_file?: string | null
    }
    export interface ValidatedSpec {
      source?: string | null
      source_type?: string | null
      timestamp?: string | null
      url?: string | null
      executive_summary?: ExecutiveSummary | null
      validation_summary?: ValidationSummary | null
      authentication?: AuthenticationSpec | null
      access_requirements?: AccessRequirements | null
      endpoints: EndpointDetails[]
      data_catalog?: DataCatalog | null
      scraper_recommendation?: ScraperRecommendation | null
      discrepancies: Discrepancy[]
      artifacts_generated: string[]
      next_steps: string[]
      collation_metadata?: CollationMetadata | null
      collation_analysis?: CollationAnalysis | null
    }
    export interface ValidationReport {
      validation_timestamp?: string | null
      input_file?: string | null
      overall_status?: types.ValidationOverallStatus | null
      overall_confidence?: number | null
      phase_validations: Record<string, PhaseValidation>
      critical_gaps: CriticalGap[]
      recommendations_for_second_pass: string[]
      validation_summary?: string | null
    }
    export interface ValidationSummary {
      phases_completed: string[]
      documentation_review?: string | null
      live_api_testing?: string | null
      discrepancies_found?: number | null
      confidence_score?: number | null
      confidence_level?: types.ConfidenceLevel | null
      recommendation?: string | null
      collation_complete?: boolean | null
      runs_analyzed?: number | null
      final_confidence_score?: number | null
      run1_confidence?: number | null
      run2_confidence?: number | null
      confidence_consistency?: string | null
      validator_status?: string | null
      discrepancies_resolved?: number | null
    }
}